version: 0.2
phases:
  install:
    runtime-versions:
        java: corretto8
  build:
    commands:
      - sam package --template-file template.yaml --s3-bucket bucketluislambda --output-template-file packaged-template.yaml
artifacts:
  files:
    - packaged-template.yml
